#!/bin/sh

## Upgrade packages, add additional repositories and update
sudo apt upgrade -y

sudo apt install -y \
  automake autoconf libreadline-dev \
  libncurses-dev libssl-dev libyaml-dev \
  libxslt-dev libffi-dev libtool unixodbc-dev \
  unzip curl \
  apt-transport-https ca-certificates curl software-properties-common

wget -qO - https://apt.thoughtbot.com/thoughtbot.gpg.key | sudo apt-key add -
sudo add-apt-repository "deb https://apt.thoughtbot.com/debian/ stable main"

wget -qO - https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

sudo apt update

## Install thoughtbot dotfiles, personal dotfiles, oh-my-zsh and asdf
git clone git://github.com/thoughtbot/dotfiles.git $HOME/.dotfiles
git clone git://github.com/conraddecker/laptop.git $HOME/.dev_machine
git clone git://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.6

## Install awscli, docker, postgres, rcm and zsh
sudo apt install -y awscli docker-ce postgresql postgresql-contrib rcm zsh

## Apply oh-my-zsh customizations and change shell accordingly
ln -s $HOME/.dev_machine/oh-my-zsh/custom/themes/cdv.zsh-theme $HOME/.oh-my-zsh/custom/themes/
sudo sed -i 's;/home/ubuntu:/bin/bash;/home/ubuntu:/usr/bin/zsh;' /etc/passwd
rm .bash_history .bash_logout .bashrc

## Run rcup
rcup -x "README*.md LICENSE" -d $HOME/.dev_machine/dotfiles -d $HOME/.dotfiles

## Configure docker
sudo usermod -aG docker ${USER}

## Setup postgres
sudo -u postgres createuser -s ubuntu

## Install Heroku
curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

## Configure asdf
cat <<EOT >> ~/.zshrc
$HOME/.asdf/asdf.sh
$HOME/.asdf/completions/asdf.bash
EOT

## Install ruby and node plugins
#source $HOME/.asdf/asdf.sh
asdf plugin-add ruby
asdf plugin-add nodejs

## Install ruby latest
# asdf install ruby latest

## Install nodejs latest
#bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
#asdf install nodejs latest
