#!/bin/sh

## Update & Upgrade
sudo apt-get update -y
sudo apt-get upgrade -y

## Install RCM
wget -qO - https://apt.thoughtbot.com/thoughtbot.gpg.key | sudo apt-key add -
echo "deb https://apt.thoughtbot.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/thoughtbot.list
sudo apt-get update -y
sudo apt-get install rcm

## Install thoughtbot & personal dotfiles
git clone git://github.com/thoughtbot/dotfiles.git $HOME/.dotfiles
git clone git://github.com/conraddecker/laptop.git $HOME/.dev_machine
rcup -x "README*.md LICENSE" -d $HOME/.dev_machine/dotfiles -d $HOME/.dotfiles

## Install zsh, apply customizations and change shell accordingly
sudo apt-get install zsh -y
git clone git://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh
ln -s $HOME/.dev_machine/oh-my-zsh/custom/themes/cdv.zsh-theme $HOME/.oh-my-zsh/custom/themes/
sudo sed -i 's;/home/ubuntu:/bin/bash;/home/ubuntu:/usr/bin/zsh;' /etc/passwd
rm .bash_history .bash_logout .bashrc

## Install docker
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
sudo apt update -y
sudo apt install docker-ce -y
sudo usermod -aG docker ${USER}

## Install Heroku
curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

## Install asdf
sudo apt install \
  automake autoconf libreadline-dev \
  libncurses-dev libssl-dev libyaml-dev \
  libxslt-dev libffi-dev libtool unixodbc-dev \
  unzip curl
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.6
echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.zshrc
echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.zshrc

## Install ruby and node plugins
source $HOME/.asdf/asdf.sh
asdf plugin-add ruby
asdf plugin-add nodejs

## Install ruby latest
# asdf install ruby latest

## Install nodejs latest
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
asdf install nodejs latest
